### ISSUE TITLE
connecting to the server with version 0.9.30, the software crashed

### ISSUE THREAD

**Issue by Putarku** [Utazukin/Ichaival#64]
After updating the Lanraragi server to version 0.9.30, the software experienced a crash issue.Here is the crash log.

```
org.json.JSONException: Value true at has_password of type java.lang.Boolean cannot be converted to int
	at org.json.JSON.typeMismatch(JSON.java:101)
	at org.json.JSONObject.getInt(JSONObject.java:490)
	at com.utazukin.ichaival.ServerManager.b(SourceFile:254)
	at com.utazukin.ichaival.ServerManager$init$1.t(SourceFile:1)
	at F3.a.n(SourceFile:9)
	at W3.J.run(SourceFile:97)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:249)
	at android.os.Looper.loop(Looper.java:337)
	at android.app.ActivityThread.main(ActivityThread.java:9572)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
	Suppressed: b4.g: [u0{Cancelling}@110af7f, Dispatchers.Main.immediate]
```

**Comment by Difegue** [comment]
I suspect this is caused by the breaking change in /api/info - I'd suggest remaining on 0.9.29 if you want to keep using Ichaival for the time being.
